### PR TITLE
use default application instead of nautilus

### PR DESCRIPTION
**Pull request by frostbane**

### CODE REVIEW

**Comment by frostbane** [comment]
Hi, I am using `pcmanfm` instead of `nautilus`, and the `open trash` button does not work for me.

`xdg-open` should use the user's preferred application to open the specified uri.

**Comment by b00f** [comment]
Does this work for other distros?

**Comment by frostbane** [comment]
My distro is fedora I have tested it only on fedora however, `xdg-open` has been there since forever, so in my opinion it should work.

If you want, you could try in your terminal `xdg-open some_picture.png` and it should open it with your default image viewer, or
`xdg-open http://some_website.com` and it should open it with your default browser.

**Comment by b00f** [comment]
@frostbane, thanks for the explanation. It looks good to me. I will update the extension soon

**Pull request merged**
